services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - ${MQTT_PORT:-1883}:1883
    environment:
      - MQTT_PASSWD=${MQTT_PASSWD}
    volumes:
      - ./data/mosquitto:/mosquitto/data
    networks:
      - net

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    ports:
      - ${ZIGBEE2MQTT_PORT:-8080}:8080
    environment:
      - TZ=${TIMEZONE}
      - MQTT_PASSWD=${MQTT_PASSWD}
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    #devices:
      # SONOFF Zigbee USB Dongle+ V2
      #- /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20240219204034-if00:/dev/ttyACM0
    networks:
      - net
    depends_on:
      - mqtt

networks:
  net:
    external: false
